version: "3.8"
services:
  database:
    image: mariadb:10.5.9
    ports:
      - "3308:3306"
    volumes:
      - ./db/seeds/test:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_ROOT_PASSWORD=iamgroot"